"""Update book user relationship

Revision ID: 715c0e644860
Revises: 8c8c99d5b60e
Create Date: 2025-01-31 23:25:51.082268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '715c0e644860'
down_revision: Union[str, None] = '8c8c99d5b60e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop existing data since we can't safely convert string user_ids to integers
    op.execute('DELETE FROM books')
    
    # Change column type to integer
    op.execute('ALTER TABLE books ALTER COLUMN user_id TYPE INTEGER USING NULL')
    
    # Add foreign key constraint
    op.create_foreign_key(None, 'books', 'user', ['user_id'], ['id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.alter_column('books', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
